/*
 * Copyright (c) 2011-2015, fortiss GmbH.
 * Licensed under the Apache License, Version 2.0.
 *
 * Use, modification and distribution are subject to the terms specified
 * in the accompanying license file LICENSE.txt located at the root directory
 * of this software distribution.
 */

package ch.iec._61400.ews._1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import ch.iec._61400.ews._1.AbortResponse;
import ch.iec._61400.ews._1.AddSubscriptionRequest;
import ch.iec._61400.ews._1.AddSubscriptionResponse;
import ch.iec._61400.ews._1.AssociateRequest;
import ch.iec._61400.ews._1.AssociateResponse;
import ch.iec._61400.ews._1.CancelRequest;
import ch.iec._61400.ews._1.CancelResponse;
import ch.iec._61400.ews._1.CommandTerminationRequest;
import ch.iec._61400.ews._1.CommandTerminationResponse;
import ch.iec._61400.ews._1.CreateDataSetRequest;
import ch.iec._61400.ews._1.CreateDataSetResponse;
import ch.iec._61400.ews._1.DeleteDataSetRequest;
import ch.iec._61400.ews._1.DeleteDataSetResponse;
import ch.iec._61400.ews._1.GetBRCBValuesRequest;
import ch.iec._61400.ews._1.GetBRCBValuesResponse;
import ch.iec._61400.ews._1.GetDataDefinitionRequest;
import ch.iec._61400.ews._1.GetDataDefinitionResponse;
import ch.iec._61400.ews._1.GetDataDirectoryRequest;
import ch.iec._61400.ews._1.GetDataDirectoryResponse;
import ch.iec._61400.ews._1.GetDataSetDirectoryRequest;
import ch.iec._61400.ews._1.GetDataSetDirectoryResponse;
import ch.iec._61400.ews._1.GetDataSetValuesRequest;
import ch.iec._61400.ews._1.GetDataSetValuesResponse;
import ch.iec._61400.ews._1.GetDataValuesRequest;
import ch.iec._61400.ews._1.GetDataValuesResponse;
import ch.iec._61400.ews._1.GetLCBValuesRequest;
import ch.iec._61400.ews._1.GetLCBValuesResponse;
import ch.iec._61400.ews._1.GetLogStatusValuesRequest;
import ch.iec._61400.ews._1.GetLogStatusValuesResponse;
import ch.iec._61400.ews._1.GetLogicalDeviceDirectoryRequest;
import ch.iec._61400.ews._1.GetLogicalDeviceDirectoryResponse;
import ch.iec._61400.ews._1.GetLogicalNodeDirectoryRequest;
import ch.iec._61400.ews._1.GetLogicalNodeDirectoryResponse;
import ch.iec._61400.ews._1.GetServerDirectoryRequest;
import ch.iec._61400.ews._1.GetServerDirectoryResponse;
import ch.iec._61400.ews._1.GetURCBValuesRequest;
import ch.iec._61400.ews._1.GetURCBValuesResponse;
import ch.iec._61400.ews._1.ObjectFactory;
import ch.iec._61400.ews._1.OperateRequest;
import ch.iec._61400.ews._1.OperateResponse;
import ch.iec._61400.ews._1.QueryLogAfterRequest;
import ch.iec._61400.ews._1.QueryLogAfterResponse;
import ch.iec._61400.ews._1.QueryLogByTimeRequest;
import ch.iec._61400.ews._1.QueryLogByTimeResponse;
import ch.iec._61400.ews._1.ReleaseRequest;
import ch.iec._61400.ews._1.RemoveSubscriptionRequest;
import ch.iec._61400.ews._1.RemoveSubscriptionResponse;
import ch.iec._61400.ews._1.ReportRequest;
import ch.iec._61400.ews._1.ReportResponse;
import ch.iec._61400.ews._1.SelectRequest;
import ch.iec._61400.ews._1.SelectResponse;
import ch.iec._61400.ews._1.SelectWithValueRequest;
import ch.iec._61400.ews._1.SelectWithValueResponse;
import ch.iec._61400.ews._1.SetBRCBValuesRequest;
import ch.iec._61400.ews._1.SetBRCBValuesResponse;
import ch.iec._61400.ews._1.SetDataSetValuesRequest;
import ch.iec._61400.ews._1.SetDataSetValuesResponse;
import ch.iec._61400.ews._1.SetDataValuesRequest;
import ch.iec._61400.ews._1.SetDataValuesResponse;
import ch.iec._61400.ews._1.SetLCBValuesRequest;
import ch.iec._61400.ews._1.SetLCBValuesResponse;
import ch.iec._61400.ews._1.SetURCBValuesRequest;
import ch.iec._61400.ews._1.SetURCBValuesResponse;
import ch.iec._61400.ews._1.TimeActivatedOperateRequest;
import ch.iec._61400.ews._1.TimeActivatedOperateResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicePortType", targetNamespace = "http://iec.ch/61400/ews/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.AssociateResponse
     */
    @WebMethod(operationName = "Associate", action = "http://iec.ch/ews/1.0/Associate")
    @WebResult(name = "AssociateResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public AssociateResponse associate(
        @WebParam(name = "AssociateRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        AssociateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.AbortResponse
     */
    @WebMethod(operationName = "Release", action = "http://iec.ch/ews/1.0/Release")
    @WebResult(name = "AbortResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public AbortResponse release(
        @WebParam(name = "ReleaseRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        ReleaseRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetServerDirectoryResponse
     */
    @WebMethod(operationName = "GetServerDirectory", action = "http://iec.ch/ews/1.0/GetServerDirectory")
    @WebResult(name = "GetServerDirectoryResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetServerDirectoryResponse getServerDirectory(
        @WebParam(name = "GetServerDirectoryRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetServerDirectoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetLogicalDeviceDirectoryResponse
     */
    @WebMethod(operationName = "GetLogicalDeviceDirectory", action = "http://iec.ch/ews/1.0/GetLogicalDeviceDirectory")
    @WebResult(name = "GetLogicalDeviceDirectoryResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetLogicalDeviceDirectoryResponse getLogicalDeviceDirectory(
        @WebParam(name = "GetLogicalDeviceDirectoryRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetLogicalDeviceDirectoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetLogicalNodeDirectoryResponse
     */
    @WebMethod(operationName = "GetLogicalNodeDirectory", action = "http://iec.ch/ews/1.0/GetLogicalNodeDirectory")
    @WebResult(name = "GetLogicalNodeDirectoryResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetLogicalNodeDirectoryResponse getLogicalNodeDirectory(
        @WebParam(name = "GetLogicalNodeDirectoryRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetLogicalNodeDirectoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetDataValuesResponse
     */
    @WebMethod(operationName = "GetDataValues", action = "http://iec.ch/ews/1.0/GetDataValues")
    @WebResult(name = "GetDataValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetDataValuesResponse getDataValues(
        @WebParam(name = "GetDataValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetDataValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SetDataValuesResponse
     */
    @WebMethod(operationName = "SetDataValues", action = "http://iec.ch/ews/1.0/SetDataValues")
    @WebResult(name = "SetDataValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SetDataValuesResponse setDataValues(
        @WebParam(name = "SetDataValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SetDataValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetDataDirectoryResponse
     */
    @WebMethod(operationName = "GetDataDirectory", action = "http://iec.ch/ews/1.0/GetDataDirectory")
    @WebResult(name = "GetDataDirectoryResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetDataDirectoryResponse getDataDirectory(
        @WebParam(name = "GetDataDirectoryRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetDataDirectoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetDataDefinitionResponse
     */
    @WebMethod(operationName = "GetDataDefinition", action = "http://iec.ch/ews/1.0/GetDataDefinition")
    @WebResult(name = "GetDataDefinitionResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetDataDefinitionResponse getDataDefinition(
        @WebParam(name = "GetDataDefinitionRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetDataDefinitionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetDataSetValuesResponse
     */
    @WebMethod(operationName = "GetDataSetValues", action = "http://iec.ch/ews/1.0/GetDataSetValues")
    @WebResult(name = "GetDataSetValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetDataSetValuesResponse getDataSetValues(
        @WebParam(name = "GetDataSetValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetDataSetValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SetDataSetValuesResponse
     */
    @WebMethod(operationName = "SetDataSetValues", action = "http://iec.ch/ews/1.0/SetDataSetValues")
    @WebResult(name = "SetDataSetValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SetDataSetValuesResponse setDataSetValues(
        @WebParam(name = "SetDataSetValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SetDataSetValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.CreateDataSetResponse
     */
    @WebMethod(operationName = "CreateDataSet", action = "http://iec.ch/ews/1.0/CreateDataSet")
    @WebResult(name = "CreateDataSetResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public CreateDataSetResponse createDataSet(
        @WebParam(name = "CreateDataSetRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        CreateDataSetRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.DeleteDataSetResponse
     */
    @WebMethod(operationName = "DeleteDataSet", action = "http://iec.ch/ews/1.0/DeleteDataSet")
    @WebResult(name = "DeleteDataSetResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public DeleteDataSetResponse deleteDataSet(
        @WebParam(name = "DeleteDataSetRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        DeleteDataSetRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetDataSetDirectoryResponse
     */
    @WebMethod(operationName = "GetDataSetDirectory", action = "http://iec.ch/ews/1.0/GetDataSetDirectory")
    @WebResult(name = "GetDataSetDirectoryResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetDataSetDirectoryResponse getDataSetDirectory(
        @WebParam(name = "GetDataSetDirectoryRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetDataSetDirectoryRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.ReportResponse
     */
    @WebMethod(operationName = "Report", action = "http://iec.ch/ews/1.0/Report")
    @WebResult(name = "ReportResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public ReportResponse report(
        @WebParam(name = "ReportRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        ReportRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.AddSubscriptionResponse
     */
    @WebMethod(operationName = "AddSubscription", action = "http://iec.ch/ews/1.0/AddSubscription")
    @WebResult(name = "AddSubscriptionResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public AddSubscriptionResponse addSubscription(
        @WebParam(name = "AddSubscriptionRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        AddSubscriptionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.RemoveSubscriptionResponse
     */
    @WebMethod(operationName = "RemoveSubscription", action = "http://iec.ch/ews/1.0/RemoveSubscription")
    @WebResult(name = "RemoveSubscriptionResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public RemoveSubscriptionResponse removeSubscription(
        @WebParam(name = "RemoveSubscriptionRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        RemoveSubscriptionRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetBRCBValuesResponse
     */
    @WebMethod(operationName = "GetBRCBValues", action = "http://iec.ch/ews/1.0/GetBRCBValues")
    @WebResult(name = "GetBRCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetBRCBValuesResponse getBRCBValues(
        @WebParam(name = "GetBRCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetBRCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SetBRCBValuesResponse
     */
    @WebMethod(operationName = "SetBRCBValues", action = "http://iec.ch/ews/1.0/SetBRCBValues")
    @WebResult(name = "SetBRCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SetBRCBValuesResponse setBRCBValues(
        @WebParam(name = "SetBRCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SetBRCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetURCBValuesResponse
     */
    @WebMethod(operationName = "GetURCBValues", action = "http://iec.ch/ews/1.0/GetURCBValues")
    @WebResult(name = "GetURCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetURCBValuesResponse getURCBValues(
        @WebParam(name = "GetURCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetURCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SetURCBValuesResponse
     */
    @WebMethod(operationName = "SetURCBValues", action = "http://iec.ch/ews/1.0/SetURCBValues")
    @WebResult(name = "SetURCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SetURCBValuesResponse setURCBValues(
        @WebParam(name = "SetURCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SetURCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetLCBValuesResponse
     */
    @WebMethod(operationName = "GetLCBValues", action = "http://iec.ch/ews/1.0/GetLCBValues")
    @WebResult(name = "GetLCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetLCBValuesResponse getLCBValues(
        @WebParam(name = "GetLCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetLCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SetLCBValuesResponse
     */
    @WebMethod(operationName = "SetLCBValues", action = "http://iec.ch/ews/1.0/SetLCBValues")
    @WebResult(name = "SetLCBValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SetLCBValuesResponse setLCBValues(
        @WebParam(name = "SetLCBValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SetLCBValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.QueryLogByTimeResponse
     */
    @WebMethod(operationName = "QueryLogByTime", action = "http://iec.ch/ews/1.0/QueryLogByTime")
    @WebResult(name = "QueryLogByTimeResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public QueryLogByTimeResponse queryLogByTime(
        @WebParam(name = "QueryLogByTimeRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        QueryLogByTimeRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.QueryLogAfterResponse
     */
    @WebMethod(operationName = "QueryLogAfter", action = "http://iec.ch/ews/1.0/QueryLogAfter")
    @WebResult(name = "QueryLogAfterResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public QueryLogAfterResponse queryLogAfter(
        @WebParam(name = "QueryLogAfterRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        QueryLogAfterRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.GetLogStatusValuesResponse
     */
    @WebMethod(operationName = "GetLogStatusValues", action = "http://iec.ch/ews/1.0/GetLogStatusValues")
    @WebResult(name = "GetLogStatusValuesResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public GetLogStatusValuesResponse getLogStatusValues(
        @WebParam(name = "GetLogStatusValuesRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        GetLogStatusValuesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SelectResponse
     */
    @WebMethod(operationName = "Select", action = "http://iec.ch/ews/1.0/Select")
    @WebResult(name = "SelectResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SelectResponse select(
        @WebParam(name = "SelectRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SelectRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.SelectWithValueResponse
     */
    @WebMethod(operationName = "SelectWithValue", action = "http://iec.ch/ews/1.0/SelectWithValue")
    @WebResult(name = "SelectWithValueResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public SelectWithValueResponse selectWithValue(
        @WebParam(name = "SelectWithValueRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        SelectWithValueRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.CancelResponse
     */
    @WebMethod(operationName = "Cancel", action = "http://iec.ch/ews/1.0/Cancel")
    @WebResult(name = "CancelResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public CancelResponse cancel(
        @WebParam(name = "CancelRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        CancelRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.OperateResponse
     */
    @WebMethod(operationName = "Operate", action = "http://iec.ch/ews/1.0/Operate")
    @WebResult(name = "OperateResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public OperateResponse operate(
        @WebParam(name = "OperateRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        OperateRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.CommandTerminationResponse
     */
    @WebMethod(operationName = "CommandTermination", action = "http://iec.ch/ews/1.0/CommandTermination")
    @WebResult(name = "CommandTerminationResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public CommandTerminationResponse commandTermination(
        @WebParam(name = "CommandTerminationRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        CommandTerminationRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ch.iec._61400.ews._1.TimeActivatedOperateResponse
     */
    @WebMethod(operationName = "TimeActivatedOperate", action = "http://iec.ch/ews/1.0/TimeActivatedOperate")
    @WebResult(name = "TimeActivatedOperateResponse", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
    public TimeActivatedOperateResponse timeActivatedOperate(
        @WebParam(name = "TimeActivatedOperateRequest", targetNamespace = "http://iec.ch/61400/ews/1.0/", partName = "parameters")
        TimeActivatedOperateRequest parameters);

}
